### PR TITLE
README changes

### PR DESCRIPTION
**Pull request by 2percentsilk**
Updates to README to address Codespaces and Remote Containers

### CODE REVIEW

**Comment by 2percentsilk** [comment]
@Chuxel we're planning to update the try-remote samples to be a bit more Codespace friendly. Can you take a quick look at the README changes?

Once we get your ack, we'll make similar changes across the other try-remote repos!

**Comment by Chuxel** [comment]
I don't think these are really entrypoints for people learning about the products as much as getting into using them, so a few thoughts:

1. I think one of the things we tried to do with these is keep the amount of text and graphics to a minimum, since if you were here, you knew what VS Code Remote - Containers was.  This is also how the docker team tends to ask people to structure DockerHub pages.  Generally if you're at the page, you know what docker and ".NET" are... so why explain what .NET is at the top.  You can include content at the end that is "About Codespaces" and "About Remote - Containers" (if not about dev containers).

    With that in mind, perhaps the text on what codespaces / remote - containers / dev containers arre could go at the end of the content and jump right into how to use the repository?

2. Style wise Greg always tells me to use **bold for UI or VS Code commands** and only use `this formatting` for code, terminal commands (a form of code), or file paths -- so maybe just use bold for things like "Open with Codespace".

3. For the images, they push things down far enough the core meat of the "try" content is pretty far down. Could we just include the section of the UI in question? (like just the code button).  We say "see here for more info" and point to docs.

4. Image formatting also looks like it got wonky when I preview: 

    image

**Comment by 2percentsilk** [comment]
Updated according to your comments @chuxel

**Comment by Chuxel** [comment]
LGTM!  I think you should have merger rights to do it whenever you are ready, but LMK if not.

**Comment by 2percentsilk** [comment]
Hmmm no write access for me but @bamurtaugh can you go ahead and merge or give me access haha?

**Comment by bamurtaugh** [comment]
Just merged! 😃

**Pull request merged**
