### PR TITLE
Revert port number to 3000

### PR DESCRIPTION
**Pull request by andrebrowne**

### CODE REVIEW

**Review by Winsway88 — APPROVED** [review]

**Review by casperdcl — APPROVED** [review]
bug introduced in #86.

The port is documented and configured as `3000` in multiple places. This PR fixes the one location where it's `9000`.

**Comment by andrebrowne** [comment]
@Chuxel Please review

**Comment by andrebrowne** [comment]
@bamurtaugh Please review

**Review by bamurtaugh — APPROVED** [review]
Thanks!

**Comment by andrebrowne** [comment]
@2percentsilk @egamma If you are Collaborators, please review

**Review by Chuxel — APPROVED** [review]

**Pull request merged**
